"""'categorynew

Revision ID: 3ffae2e9dd73
Revises: 6373504693df
Create Date: 2023-11-13 13:03:42.353340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffae2e9dd73'
down_revision: Union[str, None] = '6373504693df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nameuser', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('new_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['new_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('categorynews_new_id_fkey', 'categorynews', type_='foreignkey')
    op.drop_column('categorynews', 'new_id')
    op.add_column('news', sa.Column('cat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'categorynews', ['cat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'cat_id')
    op.add_column('categorynews', sa.Column('new_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categorynews_new_id_fkey', 'categorynews', 'news', ['new_id'], ['id'])
    op.drop_table('comments')
    # ### end Alembic commands ###
