"""'1tomanyм3'

Revision ID: 6d31e90bf38a
Revises: 1ddadb210b32
Create Date: 2023-11-11 14:16:04.614174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d31e90bf38a'
down_revision: Union[str, None] = '1ddadb210b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
