"""'db2'

Revision ID: a2a0cf1a289c
Revises: 1ed0a974fd68
Create Date: 2023-11-24 14:20:43.733288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a0cf1a289c'
down_revision: Union[str, None] = '1ed0a974fd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Genres_Films', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Genres_Films', 'films_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Genres_Films', 'films_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Genres_Films', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
